# Generated by Django 5.2.5 on 2025-08-10 11:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250810_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='priority',
        ),
        migrations.AddField(
            model_name='document',
            name='filename',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='section',
            field=models.CharField(default=22, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.category'),
        ),
    ]
